const STATUS_MESSAGE = {
    // General
    CREATE_SUCCESSFULLY: 'Create successfully',
    FORBIDDEN: 'Forbidden',
    ACTION_FAILED: 'Action failed',
    ACTION_SUCCESSFULLY: 'Action success',
    INTERNAL_SERVER_ERROR: 'Internal server error',

    //Auth
    USER_NOT_REGISTERED: 'The user is not registered',
    LOGIN_SUCCESSFULLY: 'Your login was successfully',
    GET_PROFILE_SUCCESSFULLY: 'Get profile successfully',
    LOGIN_FAIL: 'Your login failed',
    LOGIN_GOOGLE_SUCCESSFULLY: 'Auth logged with google in successful',
    LOGIN_GOOGLE_FAIL: 'Auth logged with google in failed',
    REFRESH_TOKEN_SUCCESSFULLY: 'Your refresh token was successfully',
    EMAIL_NOT_FOUND: 'Email not found',
    PLEASE_VERIFY_EMAIL: 'Please verify the email',
    INCORRECT_PASSWORD: 'Incorrect password',
    ACCOUNT_INACTIVE: 'The account inactive',
    SAME_LANGUAGE_CODE: 'Same language code',
    CHANGE_LANGUAGE_CODE_SUCCESSFULLY: 'Change language code successfully',
    REFRESH_TOKEN_INVALID: 'Refresh token invalid',
    VERIFIED_EMAIL: 'Verified email',
    RESEND_EMAIL_SUCCESSFULLY: 'Resend email successfully',
    TOKEN_INVALID: 'Token invalid',
    VERIFY_EMAIL_SUCCESSFULLY: 'Verify email successfully',
    CHANGE_PASSWORD_SUCCESSFULLY: 'Change password successfully',
    FORGOT_PASSWORD_SUCCESSFULLY: 'Forgot password successfully',
    LOGOUT_SUCCESSFULLY: 'Logout successfully',
    UNAUTHORIZED: 'Unauthorized',
    EMAIL_ALREADY_EXISTED: 'Email already existed',
    SAME_OLD_PASSWORD: 'Same old password',

    //Message
    SEND_MESSAGE_SUCCESSFULLY: 'Send message successfully',
    SEND_MESSAGE_FAIL: 'Send message failed',
    TRANSLATE_MESSAGE_SUCCESSFULLY: 'Translate message successfully',
    GET_MESSAGE_SUCCESSFULLY: 'Get message successfully',

    // Group chat
    CREATE_GROUP_SUCCESSFULLY: 'Create conversation successfully',
    UPDATE_GROUP_SUCCESSFULLY: 'Update conversation successfully',
    GROUP_NOT_FOUND: 'Conversation chat not found',
    MEMBER_NOT_FOUND: 'Member not found',
    DELETE_GROUP_SUCCESSFULLY: 'Delete conversation successfully',
    ADD_MEMBER_TO_GROUP_SUCCESSFULLY: 'Add member to conversation successfully',
    MEMBER_ALREADY_EXIST_IN_GROUP: 'Member already exist in conversation',
    DELETE_MEMBER_SUCCESSFULLY: 'Delete member from conversation successfully',
    EXCHANGE_ADMIN_ID_REQUIRED: 'Exchange admin id required',
    USER_NOT_IN_GROUP: 'User not in the conversation',
    USER_ALREADY_ENABLE_TRANSLATE: 'User already enable translate',
    ENABLE_TRANSLATE_SUCCESSFULLY: 'Enable translate successfully',
    USER_HAS_NOT_ENABLED_TRANSLATE: 'User has not enabled translate',
    EXCHANGE_ADMIN_SUCCESSFULLY: 'Echange admin successfully',
    USER_LEAVE_IN_GROUP: 'User leave in group',

    //User
    CREATE_USER_SUCCESSFULLY: 'Create user successfully',
    UPDATE_USER_SUCCESSFULLY: 'Update user successfully',
    DELETE_USER_SUCCESSFULLY: 'Delete user successfully',
    USER_NOT_FOUND: 'User not found',

    //Message
    SEND_MESSAGE_SUCCESSFULLY: 'Send message successfully',
    SEND_MESSAGE_FAIL: 'Send message failed',
    DELETE_MESSAGE_SUCCESSFULLY: 'Delete message successfully',
    RECALL_MESSAGE_SUCCESSFULLY: 'Recall message successfully',
    NO_PERMISSION_RECALL_MESSAGE: 'You have no permission to recall this message',
    NO_PERMISSION_EDIT_MESSAGE: 'You have no permission to edit this message',
    EDIT_MESSAGE_SUCCESSFULLY: 'Edit message successfully',
    MESSAGE_NOT_FOUND: 'Message not found',
    MESSAGE_TOO_OLD_TO_EDIT: 'Message too old to edit (More than 30p)',
    NO_PERMISSION_SEND_MESSAGE: 'You have no permission to send message in this conversation',
    WATCH_MESSAGE_SUCCESSFULLY: 'Watch message success',
    //Conversation
    REMOVE_CONVERSATION_SUCCESSFULLY: 'Remove conversation success',
    CONVERSATION_NOT_FOUND: 'Conversation not found',
    CONVERSATION_ACCESS_SUCCESSFULLY: 'Conversation access success',
    CONVERSATION_CREATE_SUCCESSFULLY: 'Conversation create success',
    DELETE_CONVERSATION_HISTORY_SUCCESSFULLY: 'Delete conversation history success',
    REDO_CONVERSATION_HISTORY_SUCCESSFULLY: 'Redo conversation history success',
    UPDATE_CONVERSATION_BACKGROUND_SUCCESSFULLY: 'Update conversation background success',
    UPDATE_CONVERSATION_AVATAR_SUCCESSFULLY: 'Update conversation avatar success',
    USER_WAS_BLOCKED: 'You have been blocked',
    CONVERSATION_WAS_BLOCKED: 'You have blocked this user',
    NO_PERMISSION_ACCESS_CONVERSATION: 'You have no permission to access this conversation',
    UPDATE_BACKGROUND_CONVERSATION_SUCCESSFULLY: 'Update background conversation success',
    NO_PERMISSION_UPDATE_BACKGROUND: 'You have no permission to update background',
    UPDATE_AVATAR_CONVERSATION_SUCCESSFULLY: 'Update avatar conversation success',
    NO_PERMISSION_UPDATE_AVATAR: 'You have no permission to update avatar',
    NO_PERMISSION_BLOCK_USER: 'You have no permission to block user',
    NO_PERMISSION_UN_BLOCK_USER: 'You have no permission to un-block user',
    GET_BLOCK_USER_SUCCESSFULLY: 'Get block list success',
    BLOCK_USER_SUCCESSFULLY: 'Block user success',
    UN_BLOCK_USER_SUCCESSFULLY: 'Un-block user success',
    USER_AlREADY_BLOCKED: 'User is already blocked',
    NO_PERMISSION_REMOVE_HISTORY_CONVERSATION: 'No permission to remove conversation history',
    //Friend
    FRIEND_REQUEST_SENT_SUCCESSFULLY: 'Friend request sent',
    FRIEND_REQUEST_SENT_FAIL: 'Friend request sent failed',
    ACCEPT_FRIEND_SUCCESSFULLY: 'Accept friend success',
    ACCEPT_FRIEND_FAIL: 'Accept friend failed',
    REJECT_FRIEND_SUCCESSFULLY: 'Reject friend success',
    REJECT_FRIEND_FAIL: 'Reject friend failed',
    ALREADY_FRIEND: 'Your are already friend with this user',
    DELETE_FRIEND_SUCCESSFULLY: 'Delete friend success',
    NO_PERMISSION_ACCEPT_REQUEST: 'You have no permission to accept request',
    NO_PERMISSION_REJECT_REQUEST: 'You have no permission to reject request',
    NO_PERMISSION_REMOVE_REQUEST: 'You have no permission to remove request',
    REMOVE_FRIEND_REQUEST_SUCCESSFULLY: 'Remove friend request success',
    REMOVE_FRIEND_SUCCESSFULLY: 'Remove friend success',
    REQUEST_NOT_FOUND: 'Request not found',
    LIMIT_TRANSLATE: 'The number of translated characters has reached the limit',

    //Emoji
    ADD_EMOJI_MESSAGE_SUCCESSFULLY: 'Add emoji success',
    UPDATE_EMOJI_MESSAGE_SUCCESSFULLY: 'Update emoji success',
    REMOVE_EMOJI_MESSAGE_SUCCESSFULLY: 'Remove emoji success',
    NOT_YOUR_EMOJI: 'Not your emoji',

    // Payment
    CREATE_PAYMENT_MOMO_LINK_SUCCESSFULLY: 'Create momo payment link successfully',
};

module.exports = STATUS_MESSAGE;
